---
title: "BEST Data Review Shiny App Notes"
format:
    html
code-tools: true
---


## Prototyping

The `app.py` file contains the top level structure of the app, pulling static datasets `dta` and `dta_info` from disk into global variables. Each of these is made "reactive" by defining `dtar` and `dta_infor` in the server.

```{dot}
digraph data_review1_module{
    node [shape=box]
    node [shape=none]
    dta
    dta_info
    subgraph cluster_0 {
        style=rounded
        label=input
        node [shape=box]
        variables [label="(first)variables"]
        dt_start [label="(first)dt_start"]
        days [label="(first)days"]
    }
    subgraph cluster_1 {
        label=output
        style=rounded
        node [shape=box]
        plot1
    }
    node [shape=oval]
    dtar
    dta_infor
    data_review1_server [label="data_review1_server('first')"]
    dta -> dtar
    dta_info -> dta_infor
    dtar -> data_review1_server
    dta_infor -> data_review1_server
    dt_start -> data_review1_server
    variables -> data_review1_server
    days -> data_review1_server
    data_review1_server -> plot1
}
```

The `data_review1.py` module implements both the input controls for limiting/selecting which data will be shown, and the output plot in which this data will be presented. A specific unnamed instance of this module is created in the top-level server function with module id "first".

Within the module, the `Variable` list handles multiple selection using shift and control keys. The `Start Date` control shows a graphical date selector, but has no effect until a day-of-month is chosen. The `Days` control is limited to 366 days following the `Start Date`.

